Transform {
  _readableState: ReadableState {
    objectMode: false,
    highWaterMark: 16384,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: null,
    pipesCount: 0,
    flowing: false,
    ended: true,
    endEmitted: true,
    reading: false,
    sync: false,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    paused: false,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: false,
    decoder: null,
    encoding: null
  },
  readable: false,
  _events: [Object: null prototype] {
    prefinish: [Function: prefinish],
    close: [ [Function], [Function: onclose] ],
    end: [Function: onend],
    finish: [Function: onfinish],
    error: [Function: onerror]
  },
  _eventsCount: 5,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: true,
    ended: true,
    finished: true,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    onwrite: [Function: bound onwrite],
    writecb: null,
    writelen: 0,
    bufferedRequest: null,
    lastBufferedRequest: null,
    pendingcb: 0,
    prefinished: true,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: false,
    bufferedRequestCount: 0,
    corkedRequestsFree: {
      next: null,
      entry: null,
      finish: [Function: bound onCorkedFinish]
    }
  },
  writable: false,
  allowHalfOpen: true,
  _transformState: {
    afterTransform: [Function: bound afterTransform],
    needTransform: false,
    transforming: false,
    writecb: null,
    writechunk: null,
    writeencoding: null
  },
  _transform: [Function: transform],
  _flush: [Function: flush],
  socket: TLSSocket {
    _tlsOptions: {
      allowHalfOpen: undefined,
      pipe: false,
      secureContext: [SecureContext],
      isServer: false,
      requestCert: true,
      rejectUnauthorized: true,
      session: undefined,
      ALPNProtocols: undefined,
      requestOCSP: undefined,
      enableTrace: undefined
    },
    _secureEstablished: true,
    _securePending: false,
    _newSessionPending: false,
    _controlReleased: true,
    _SNICallback: null,
    servername: ' www.youtube.com',
    alpnProtocol: false,
    authorized: true,
    authorizationError: null,
    encrypted: true,
    _events: [Object: null prototype] {
      close: [Array],
      end: [Function: onReadableStreamEnd],
      newListener: [Function: keylogNewListener],
      secure: [Function: onConnectSecure],
      session: [Function],
      free: [Function: onFree],
      agentRemove: [Function: onRemove],
      error: [Function]
    },
    _eventsCount: 8,
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'www.youtube.com',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: true,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: false,
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: undefined,
    _server: null,
    ssl: null,
    _requestCert: true,
    _rejectUnauthorized: true,
    parser: null,
    _httpMessage: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'POST /comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D HTTP/1.1\r\n' +
        'user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0\r\n' +
        'host:  www.youtube.com\r\n' +
        'accept: */*\r\n' +
        'accept-language: en-CA,en-US;q=0.7,en;q=0.3\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-youtube-client-name: 1\r\n' +
        'x-youtube-client-version: 2.20191017.04.00\r\n' +
        'x-youtube-page-cl: 275134860\r\n' +
        'x-youtube-page-label: youtube.ytfe.desktop_20191016_4_RC0\r\n' +
        'x-youtube-variants-checksum: 06cac2fe9602b1223148e475d9b658ce\r\n' +
        'x-youtube-utc-offset: -240\r\n' +
        'x-youtube-ad-signals: dt=1571497349591&flash=0&frm&u_tz=-240&u_his=4&u_java&u_h=768&u_w=1366&u_ah=743&u_aw=1366&u_cd=24&u_nplug&u_nmime&bc=29&bih=602&biw=647&brdim=0%2C25%2C0%2C25%2C1366%2C25%2C1366%2C715%2C659%2C602&vis=1&wgl=true&ca_type=image&bid=ANyPxKqzfUO30HRv0M2H6AeWGxX8ZZbZGemwvq0W0AIrI7kOTmEENhSSeMo-Viiph8qE-lYLxF5UUdYjf3XxCFJTmxvxmocoxg\r\n' +
        'x-spf-referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-spf-previous: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'content-type: application/x-www-form-urlencoded\r\n' +
        'content-length: 280\r\n' +
        'dnt: 1\r\n' +
        'connection: keep-alive\r\n' +
        'te: Trailers\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      emit: [Function],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(res)]: TLSWrap {
      _parent: [TCP],
      _parentWrap: undefined,
      _secureContext: [SecureContext],
      reading: true,
      onhandshakestart: [Function: noop],
      onhandshakedone: [Function],
      onocspresponse: [Function: onocspresponse],
      onnewsession: [Function: onnewsessionclient],
      onkeylog: [Function: onkeylogclient],
      onerror: [Function: onerror],
      [Symbol(owner)]: [Circular]
    },
    [Symbol(asyncId)]: 1068,
    [Symbol(kHandle)]: null,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kBytesRead)]: 577,
    [Symbol(kBytesWritten)]: 1872,
    [Symbol(connect-options)]: {
      rejectUnauthorized: true,
      ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      checkServerIdentity: [Function: checkServerIdentity],
      minDHSize: 1024,
      path: null,
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'www.youtube.com',
      port: 443,
      hostname: 'www.youtube.com',
      hash: null,
      search: null,
      pathname: '/comment_service_ajax',
      href: 'https://www.youtube.com/comment_service_ajax',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: false,
      cache: false,
      useElectronNet: false,
      body: [FormData],
      method: 'POST',
      _defaultAgent: [Agent],
      servername: ' www.youtube.com',
      _agentKey: 'www.youtube.com:443::::::::: www.youtube.com:::::::::',
      encoding: null,
      singleUse: true
    }
  },
  connection: TLSSocket {
    _tlsOptions: {
      allowHalfOpen: undefined,
      pipe: false,
      secureContext: [SecureContext],
      isServer: false,
      requestCert: true,
      rejectUnauthorized: true,
      session: undefined,
      ALPNProtocols: undefined,
      requestOCSP: undefined,
      enableTrace: undefined
    },
    _secureEstablished: true,
    _securePending: false,
    _newSessionPending: false,
    _controlReleased: true,
    _SNICallback: null,
    servername: ' www.youtube.com',
    alpnProtocol: false,
    authorized: true,
    authorizationError: null,
    encrypted: true,
    _events: [Object: null prototype] {
      close: [Array],
      end: [Function: onReadableStreamEnd],
      newListener: [Function: keylogNewListener],
      secure: [Function: onConnectSecure],
      session: [Function],
      free: [Function: onFree],
      agentRemove: [Function: onRemove],
      error: [Function]
    },
    _eventsCount: 8,
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'www.youtube.com',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: true,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: false,
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: undefined,
    _server: null,
    ssl: null,
    _requestCert: true,
    _rejectUnauthorized: true,
    parser: null,
    _httpMessage: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'POST /comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D HTTP/1.1\r\n' +
        'user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0\r\n' +
        'host:  www.youtube.com\r\n' +
        'accept: */*\r\n' +
        'accept-language: en-CA,en-US;q=0.7,en;q=0.3\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-youtube-client-name: 1\r\n' +
        'x-youtube-client-version: 2.20191017.04.00\r\n' +
        'x-youtube-page-cl: 275134860\r\n' +
        'x-youtube-page-label: youtube.ytfe.desktop_20191016_4_RC0\r\n' +
        'x-youtube-variants-checksum: 06cac2fe9602b1223148e475d9b658ce\r\n' +
        'x-youtube-utc-offset: -240\r\n' +
        'x-youtube-ad-signals: dt=1571497349591&flash=0&frm&u_tz=-240&u_his=4&u_java&u_h=768&u_w=1366&u_ah=743&u_aw=1366&u_cd=24&u_nplug&u_nmime&bc=29&bih=602&biw=647&brdim=0%2C25%2C0%2C25%2C1366%2C25%2C1366%2C715%2C659%2C602&vis=1&wgl=true&ca_type=image&bid=ANyPxKqzfUO30HRv0M2H6AeWGxX8ZZbZGemwvq0W0AIrI7kOTmEENhSSeMo-Viiph8qE-lYLxF5UUdYjf3XxCFJTmxvxmocoxg\r\n' +
        'x-spf-referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-spf-previous: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'content-type: application/x-www-form-urlencoded\r\n' +
        'content-length: 280\r\n' +
        'dnt: 1\r\n' +
        'connection: keep-alive\r\n' +
        'te: Trailers\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      emit: [Function],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(res)]: TLSWrap {
      _parent: [TCP],
      _parentWrap: undefined,
      _secureContext: [SecureContext],
      reading: true,
      onhandshakestart: [Function: noop],
      onhandshakedone: [Function],
      onocspresponse: [Function: onocspresponse],
      onnewsession: [Function: onnewsessionclient],
      onkeylog: [Function: onkeylogclient],
      onerror: [Function: onerror],
      [Symbol(owner)]: [Circular]
    },
    [Symbol(asyncId)]: 1068,
    [Symbol(kHandle)]: null,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kBytesRead)]: 577,
    [Symbol(kBytesWritten)]: 1872,
    [Symbol(connect-options)]: {
      rejectUnauthorized: true,
      ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      checkServerIdentity: [Function: checkServerIdentity],
      minDHSize: 1024,
      path: null,
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'www.youtube.com',
      port: 443,
      hostname: 'www.youtube.com',
      hash: null,
      search: null,
      pathname: '/comment_service_ajax',
      href: 'https://www.youtube.com/comment_service_ajax',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: false,
      cache: false,
      useElectronNet: false,
      body: [FormData],
      method: 'POST',
      _defaultAgent: [Agent],
      servername: ' www.youtube.com',
      _agentKey: 'www.youtube.com:443::::::::: www.youtube.com:::::::::',
      encoding: null,
      singleUse: true
    }
  },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: false,
  headers: {
    'cache-control': 'no-cache',
    'content-type': 'text/html; charset=utf-8',
    p3p: 'CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."',
    'content-length': '0',
    expires: 'Tue, 27 Apr 1971 19:44:06 EST',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'strict-transport-security': 'max-age=31536000',
    date: 'Sat, 19 Oct 2019 16:21:21 GMT',
    server: 'YouTube Frontend Proxy',
    'x-xss-protection': '0',
    'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000'
  },
  rawHeaders: [
    'Cache-Control',
    'no-cache',
    'Content-Type',
    'text/html; charset=utf-8',
    'P3P',
    'CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=en for more info."',
    'Content-Length',
    '0',
    'Expires',
    'Tue, 27 Apr 1971 19:44:06 EST',
    'X-Content-Type-Options',
    'nosniff',
    'X-Frame-Options',
    'SAMEORIGIN',
    'Strict-Transport-Security',
    'max-age=31536000',
    'Date',
    'Sat, 19 Oct 2019 16:21:21 GMT',
    'Server',
    'YouTube Frontend Proxy',
    'X-XSS-Protection',
    '0',
    'Alt-Svc',
    'quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000'
  ],
  trailers: {},
  rawTrailers: [],
  aborted: false,
  upgrade: false,
  url: 'https://www.youtube.com/comment_service_ajax',
  method: null,
  statusCode: 200,
  statusMessage: 'OK',
  client: TLSSocket {
    _tlsOptions: {
      allowHalfOpen: undefined,
      pipe: false,
      secureContext: [SecureContext],
      isServer: false,
      requestCert: true,
      rejectUnauthorized: true,
      session: undefined,
      ALPNProtocols: undefined,
      requestOCSP: undefined,
      enableTrace: undefined
    },
    _secureEstablished: true,
    _securePending: false,
    _newSessionPending: false,
    _controlReleased: true,
    _SNICallback: null,
    servername: ' www.youtube.com',
    alpnProtocol: false,
    authorized: true,
    authorizationError: null,
    encrypted: true,
    _events: [Object: null prototype] {
      close: [Array],
      end: [Function: onReadableStreamEnd],
      newListener: [Function: keylogNewListener],
      secure: [Function: onConnectSecure],
      session: [Function],
      free: [Function: onFree],
      agentRemove: [Function: onRemove],
      error: [Function]
    },
    _eventsCount: 8,
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: 'www.youtube.com',
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: false,
      emitClose: false,
      autoDestroy: false,
      destroyed: true,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: false,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: false,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: false,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: false,
    allowHalfOpen: false,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: undefined,
    _server: null,
    ssl: null,
    _requestCert: true,
    _rejectUnauthorized: true,
    parser: null,
    _httpMessage: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Circular],
      connection: [Circular],
      _header: 'POST /comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D HTTP/1.1\r\n' +
        'user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0\r\n' +
        'host:  www.youtube.com\r\n' +
        'accept: */*\r\n' +
        'accept-language: en-CA,en-US;q=0.7,en;q=0.3\r\n' +
        'accept-encoding: gzip, deflate, br\r\n' +
        'referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-youtube-client-name: 1\r\n' +
        'x-youtube-client-version: 2.20191017.04.00\r\n' +
        'x-youtube-page-cl: 275134860\r\n' +
        'x-youtube-page-label: youtube.ytfe.desktop_20191016_4_RC0\r\n' +
        'x-youtube-variants-checksum: 06cac2fe9602b1223148e475d9b658ce\r\n' +
        'x-youtube-utc-offset: -240\r\n' +
        'x-youtube-ad-signals: dt=1571497349591&flash=0&frm&u_tz=-240&u_his=4&u_java&u_h=768&u_w=1366&u_ah=743&u_aw=1366&u_cd=24&u_nplug&u_nmime&bc=29&bih=602&biw=647&brdim=0%2C25%2C0%2C25%2C1366%2C25%2C1366%2C715%2C659%2C602&vis=1&wgl=true&ca_type=image&bid=ANyPxKqzfUO30HRv0M2H6AeWGxX8ZZbZGemwvq0W0AIrI7kOTmEENhSSeMo-Viiph8qE-lYLxF5UUdYjf3XxCFJTmxvxmocoxg\r\n' +
        'x-spf-referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'x-spf-previous: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
        'content-type: application/x-www-form-urlencoded\r\n' +
        'content-length: 280\r\n' +
        'dnt: 1\r\n' +
        'connection: keep-alive\r\n' +
        'te: Trailers\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      emit: [Function],
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(res)]: TLSWrap {
      _parent: [TCP],
      _parentWrap: undefined,
      _secureContext: [SecureContext],
      reading: true,
      onhandshakestart: [Function: noop],
      onhandshakedone: [Function],
      onocspresponse: [Function: onocspresponse],
      onnewsession: [Function: onnewsessionclient],
      onkeylog: [Function: onkeylogclient],
      onerror: [Function: onerror],
      [Symbol(owner)]: [Circular]
    },
    [Symbol(asyncId)]: 1068,
    [Symbol(kHandle)]: null,
    [Symbol(lastWriteQueueSize)]: 0,
    [Symbol(timeout)]: null,
    [Symbol(kBuffer)]: null,
    [Symbol(kBufferCb)]: null,
    [Symbol(kBufferGen)]: null,
    [Symbol(kBytesRead)]: 577,
    [Symbol(kBytesWritten)]: 1872,
    [Symbol(connect-options)]: {
      rejectUnauthorized: true,
      ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
      checkServerIdentity: [Function: checkServerIdentity],
      minDHSize: 1024,
      path: null,
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'www.youtube.com',
      port: 443,
      hostname: 'www.youtube.com',
      hash: null,
      search: null,
      pathname: '/comment_service_ajax',
      href: 'https://www.youtube.com/comment_service_ajax',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: false,
      cache: false,
      useElectronNet: false,
      body: [FormData],
      method: 'POST',
      _defaultAgent: [Agent],
      servername: ' www.youtube.com',
      _agentKey: 'www.youtube.com:443::::::::: www.youtube.com:::::::::',
      encoding: null,
      singleUse: true
    }
  },
  _consuming: false,
  _dumped: false,
  req: ClientRequest {
    _events: [Object: null prototype] {
      error: [Array],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: ' www.youtube.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 8,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.youtube.com',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1068,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 577,
      [Symbol(kBytesWritten)]: 1872,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: ' www.youtube.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 8,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'www.youtube.com',
      _readableState: [ReadableState],
      readable: false,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 1068,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 577,
      [Symbol(kBytesWritten)]: 1872,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D HTTP/1.1\r\n' +
      'user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0\r\n' +
      'host:  www.youtube.com\r\n' +
      'accept: */*\r\n' +
      'accept-language: en-CA,en-US;q=0.7,en;q=0.3\r\n' +
      'accept-encoding: gzip, deflate, br\r\n' +
      'referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
      'x-youtube-client-name: 1\r\n' +
      'x-youtube-client-version: 2.20191017.04.00\r\n' +
      'x-youtube-page-cl: 275134860\r\n' +
      'x-youtube-page-label: youtube.ytfe.desktop_20191016_4_RC0\r\n' +
      'x-youtube-variants-checksum: 06cac2fe9602b1223148e475d9b658ce\r\n' +
      'x-youtube-utc-offset: -240\r\n' +
      'x-youtube-ad-signals: dt=1571497349591&flash=0&frm&u_tz=-240&u_his=4&u_java&u_h=768&u_w=1366&u_ah=743&u_aw=1366&u_cd=24&u_nplug&u_nmime&bc=29&bih=602&biw=647&brdim=0%2C25%2C0%2C25%2C1366%2C25%2C1366%2C715%2C659%2C602&vis=1&wgl=true&ca_type=image&bid=ANyPxKqzfUO30HRv0M2H6AeWGxX8ZZbZGemwvq0W0AIrI7kOTmEENhSSeMo-Viiph8qE-lYLxF5UUdYjf3XxCFJTmxvxmocoxg\r\n' +
      'x-spf-referer: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
      'x-spf-previous: https://www.youtube.com/watch?v=Z2qi_pivYSM\r\n' +
      'content-type: application/x-www-form-urlencoded\r\n' +
      'content-length: 280\r\n' +
      'dnt: 1\r\n' +
      'connection: keep-alive\r\n' +
      'te: Trailers\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object]
    },
    socketPath: undefined,
    method: 'POST',
    path: '/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: 'https://www.youtube.com/comment_service_ajax',
      method: null,
      statusCode: 200,
      statusMessage: 'OK',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      requestUrl: 'https://www.youtube.com/comment_service_ajax',
      retryCount: 0,
      timings: [Object],
      redirectUrls: [],
      request: [Object],
      emit: [Function]
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    emit: [Function],
    [Symbol(kNeedDrain)]: false,
    [Symbol(isCorked)]: false,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'user-agent': [Array],
      host: [Array],
      accept: [Array],
      'accept-language': [Array],
      'accept-encoding': [Array],
      referer: [Array],
      'x-youtube-client-name': [Array],
      'x-youtube-client-version': [Array],
      'x-youtube-page-cl': [Array],
      'x-youtube-page-label': [Array],
      'x-youtube-variants-checksum': [Array],
      'x-youtube-utc-offset': [Array],
      'x-youtube-ad-signals': [Array],
      'x-spf-referer': [Array],
      'x-spf-previous': [Array],
      'content-type': [Array],
      'content-length': [Array],
      dnt: [Array],
      connection: [Array],
      te: [Array]
    }
  },
  requestUrl: 'https://www.youtube.com/comment_service_ajax',
  retryCount: 0,
  timings: {
    start: 1571502081273,
    socket: 1571502081277,
    lookup: 1571502081277,
    connect: 1571502081295,
    upload: 1571502081349,
    response: 1571502081433,
    end: 1571502081434,
    error: null,
    phases: {
      wait: 4,
      dns: 0,
      tcp: 18,
      request: 54,
      firstByte: 84,
      download: 1,
      total: 161
    }
  },
  redirectUrls: [],
  request: {
    gotOptions: {
      path: '/comment_service_ajax?action_get_comments=1&pbj=1&ctoken=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&continuation=EkQSC1oycWlfcGl2WVNNwAEAyAEA4AEBogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgG&itct=CCwQ6TgYACITCLv2o7rdqOUCFQV1MAodkwIL3Uijwr3F6d-otWc%3D',
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'www.youtube.com',
      port: null,
      hostname: 'www.youtube.com',
      hash: null,
      search: null,
      pathname: '/comment_service_ajax',
      href: 'https://www.youtube.com/comment_service_ajax',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: false,
      cache: false,
      useElectronNet: false,
      body: undefined,
      method: 'POST'
    }
  },
  setTimeout: [Function: bound setTimeout],
  body: ''
}
